### ISSUE TITLE
installation error

### ISSUE THREAD

**Issue by fengdong110** [sfu-compbio/sinvict#1]
error:
        Caller.cpp: 467: error: Call overloaded 'to_string (int)' is ambiguous

 to_string (int) overloaded 。

how to solve this problem？3q.

**Comment by fengdong110** [comment]
Detailed error：

make

g ++ -c -g -std = c ++ 0x main.cpp -o main.o
g ++ -c -g -std = c ++ 0x Caller.cpp -o Caller.o
Caller.cpp: In member function 'std :: vector <Location, std :: allocator <Location>> Caller :: callHomopolymerFilter (std :: vector <Location, std :: allocator <Location>>)':
Caller.cpp: 467: error: Call overloaded 'to_string (int)' is ambiguous
/usr/lib/gcc/x86_64-redhat-linux/4.4.6/../../../../include/c++/4.4.6/bits/basic_string.h:2604: Note: Alternative to : std :: string std :: to_string (long long int)
/usr/lib/gcc/x86_64-redhat-linux/4.4.6/../../../../include/c++/4.4.6/bits/basic_string.h:2610: Note: std :: string std :: to_string (long long unsigned int)
/usr/lib/gcc/x86_64-redhat-linux/4.4.6/../../../../include/c++/4.4.6/bits/basic_string.h:2616: Note: std :: string std :: to_string (long double)

**Comment by ckockan** [comment]
Your compiler version (gcc 4.4) does not support some of the newer C++11 features. For a longer explanation see: http://stackoverflow.com/questions/20090651/compilation-error-while-using-to-string-in-c-program
