### ISSUE TITLE
Installation Issue

### ISSUE THREAD

**Issue by kkwolf** [sfu-compbio/sinvict#2]
Hello. I am relatively new to command line, and apologize if there is a simple fix to something I am experiencing. I have come across an issue when attempting to install sinvict. I have downloaded, compiled and installed Boost 1_62 and G++-6.1.0.

Below is a fatal error that occurs when I attempt the make command in the sinvict directory. 

$ make 
g++ -c -g -std=c++0x main.cpp -o main.o
g++ -c -g -std=c++0x Sample.cpp -o Sample.o
g++ -c -g -std=c++0x ReadcountEntry.cpp -o ReadcountEntry.o
g++ -c -g -std=c++0x Allele.cpp -o Allele.o
main.cpp:1:10: fatal error: 'boost/program_options/options_description.hpp' file
      not found
# include <boost/program_options/options_description.hpp>

```
     ^
```

1 error generated.
make: **\* [main.o] Error 1
make: **\* Waiting for unfinished jobs....

Thanks so much in advance, and please let me know if you need to know anything more.

**Comment by kkwolf** [comment]
![screenshot 2016-10-07 13 05 40](https://cloud.githubusercontent.com/assets/22669987/19200525/1d0af534-8c8f-11e6-9e55-ca17e830259d.png)
The file does indeed exist in the boost directory (boost/program_options/options_description.hpp)

**Comment by ckockan** [comment]
Hi kkwolf, your boost and g++ versions looks good so I suspect that this is a linker issue. If that is the case you might need to edit the Makefile.

As a first step towards diagnosing the problem, would it be possible for you to try and compile a very simple test program that uses the boost header  (boost/program_options/options_description.hpp) that causes the issue? Something as simple as the test program in the following link should suffice:

http://stackoverflow.com/questions/29354201/linking-error-for-boostprogram-options

Then, if indeed this is a linker issue, we can figure out what you need to change in the Makefile.

**Comment by kkwolf** [comment]
Thank you. 

Below are the paths to Boost.

/Users/kerriwolf/boost_1_62_0/boost/program_options/options_description.hpp
/Users/kerriwolf/boost_1_62_0/stage/lib/libboost_program_options.a
/Users/kerriwolf/boost_1_62_0/stage/lib/libboost_program_options.dylib

I attempted a program, but I am having some difficulty. I am very new to command line and programming. Do you think you would be able to demonstrate specifically what I should do?

**Comment by fhach** [comment]
Please be advised that sinvict has not been tested on OSX. It has been implemented and tested on linux machine. 

As for your issue. I have downloaded the latest version of boost and compiled in my download folders. Please modify the Makefile in sinvict folder as follows and update the path

`CFLAGS = -c -g -std=c++0x -I/Users/kerriwolf/boost_1_62_0/`
`LDFLAGS = -lz -L/Users/kerriwolf/boost_1_62_0/stage/lib/ -lboost_program_options`

Also in your command line add 
`$ export DYLD_LIBRARY_PATH=/Users/kerriwolf/boost_1_62_0/stage/lib/`

Finally,  make clean && make and try sinvict.
`$ make clean`
`$ make`
`$ ./sinvict`

Alternatively, you can install boost through brew or macports. Doing so, you dont have to modify anything as far as I can recall.

**Comment by kkwolf** [comment]
Thanks so much @fhach. I really appreciate the very clear instructions! I have successfully installed the program and look forward to putting it to use. 

Have a great day!
Kerri
