### ISSUE TITLE
error in running sample

### ISSUE THREAD

**Issue by Krisloveless** [sfu-compbio/sinvict#3]
i used this "./sinvict ../mixture_5-95.readcount -o ../" 
but error occured:"terminate called after throwing an instance of 'boost::exception_detail::clone_implboost::exception_detail::error_info_injector<boost::bad_any_cast >'
  what():  boost::bad_any_cast: failed conversion using boost::any_cast
Aborted (core dumped)"

**Comment by Krisloveless** [comment]
thank you very much in advance

**Comment by ckockan** [comment]
Hi Kris, what version of boost are you using? I'm trying to reproduce the error. I noticed something with your command line but that should not be causing the issue:

"./sinvict ../mixture_5-95.readcount -o ../" 
- I believe you might have missed the -t flag before the input directory while typing. The program prints an error message and exits if that is missing so that is probably not the cause of the error.
- The parameter after -t should not be a file, it should be a directory that contains only readcount files. Like "../my_mixtures". But still your command line would cause the program to print a message saying that ../mixture_5-95.readcount is not a directory and exit so that is not likely the source of the error either.

That leaves boost version incompatibility as the probable candidate which causes the error but it might help if you copy-and-paste the complete command line and error message along with your boost version.

**Comment by Krisloveless** [comment]
Hi ckockan,thanks for your reply!I also tried "./sinvict -t ../place/ -o ." but it doesn't work either.(../place is where i put readcount files.)
![image](https://cloud.githubusercontent.com/assets/15829091/19604955/2f0fdfae-97ea-11e6-91a0-e1a45b059f95.png)
My boost version is the newest version 1.62.0. The make process produced no error.

**Comment by Krisloveless** [comment]
it said 
![image](https://cloud.githubusercontent.com/assets/15829091/19605191/50e46392-97eb-11e6-9ec1-0920ecec26cb.png)

**Comment by Krisloveless** [comment]
kris@nanopore:~/sinvict$ ./sinvict -t ../place/ -o .

character conversion failed

SiNVICT: Ultra Sensitive Detection of Single Nucleotide Variants and Indels in Circulating Tumour DNA.

Allowed arguments:
  -h [ --help ]                      Print help message.
  -e [ --error-rate ] arg            Error rate for the sequencing platform
                                     used.
  -m [ --min-depth ] arg             Minimum Read Depth required for high
                                     confidence in a call.
  -l [ --left-strand-bias ] arg      Lower limit for the strand bias value
                                     interval to be used in assessing the
                                     confidence of a call.
  -r [ --right-strand-bias ] arg     Upper limit for the strand bias value
                                     interval to be used in assessing the
                                     confidence of a call.
  -f [ --read-end-fraction ] arg     Average position of the called base on the
                                     reads supporting the call as a fraction.
                                     End values such as 0.01 as useful for
                                     filtering read end artifacts.
  -q [ --qscore-cutoff ] arg         Cutoff value for the qScore assigned to
                                     each call by the Poisson model used.
  -t [ --tumor-directory-path ] arg  Specifies directory for the input files.
  -o [ --output-directory-path ] arg Specifies directory for the output files.

terminate called after throwing an instance of 'boost::exception_detail::clone_implboost::exception_detail::error_info_injector<boost::bad_any_cast >'
  what():  boost::bad_any_cast: failed conversion using boost::any_cast
Aborted (core dumped)

**Comment by ckockan** [comment]
I see. I did not think the command-line was the issue anyway, those cases are handled correctly by sinvict. Most likely something to do with your boost installation/configuration.

In your detailed output I see that boost program options throws a "character conversion failed" error, followed by the initial error message you posted. I can't replicate the same issue with my installation but after some search I might have found a potential solution to your problem. This question on the following link seems very similar to your issue, might be worth checking out to see if any of the suggested solutions work for you as well:

http://stackoverflow.com/questions/35382902/boost-program-options-throws-character-conversion-failed

**Comment by Krisloveless** [comment]
I tried that but failed. Maybe it has something to do with the boost version. I'll try and see if a lower version could handle this.

**Comment by Krisloveless** [comment]
Hi ckockan, finally I solve the problem! I delete all the old versions in /usr/include, recompile the program and refresh the ldconfig. Thanks for your patience!
