### ISSUE TITLE
Can SiNVICT call the somatic mutation?

### ISSUE THREAD

**Issue by Tinalxt** [sfu-compbio/sinvict#4]
Hi~ I wonder if SiNVICT can call the somatic mutation? Such as a pair of tumor-nomal sample.

**Comment by MIAOKUI** [comment]
I also have this question

**Comment by ckockan** [comment]
Yes, that is possible. You need to run SiNVICT separately on the tumor and normal sample. Afterwards, you should subtract the mutations which were also detected in the normal sample from the set of variants called in the tumor sample.
